In [1]:
import sys
import inspect
from importlib import reload

import numpy as np
import numexpr as ne
import matplotlib.pyplot as plt

import quvac
from quvac.paraxial_gaussian import ParaxialGaussianAnalytic
from quvac.field import ExternalField
from quvac.vacuum_emission import VacuumEmission

In [2]:
field_1 = {
    "field_type": "paraxial_gaussian_analytic",
    "focus_x": (0.,0.,0.),
    "focus_t": 0.,
    "theta": 0,
    "phi": 0,
    "beta": 0,
    "lmbd": 800e-9,
    "w0": 2*800e-9,
    "tau": 25e-15,
    # "E0": 1e7,
    "W": 25,
    "phase0": 0,
}

field_2 = {
    "field_type": "paraxial_gaussian_analytic",
    "focus_x": (0.,0.,0.),
    "focus_t": 0.,
    "theta": 180,
    "phi": 0,
    "beta": 0,
    "lmbd": 800e-9,
    "w0": 2*800e-9,
    "tau": 25e-15,
    "E0": 1e8,
    "phase0": 0,
}

fields_params = [field_1, field_2]

x0 = 8e-6
x = np.linspace(-x0,x0,101).reshape((-1,1,1))
y0 = 8e-6
y = np.linspace(-y0,y0,121).reshape((1,-1,1))
z0 = 16e-6
z = np.linspace(-z0,z0,201).reshape((1,1,-1))
grid = (x, y, z)

# field1 = ParaxialGaussianAnalytic(field_1, grid)
field = ExternalField(fields_params, grid)

In [3]:
vacem = VacuumEmission(field)

/home/maximus/Research/github/quantum-vacuum/src/quvac/vacuum_emission.py:93: RuntimeWarning: invalid value encountered in divide
  self.__dict__[f'k{ax}_unit'] = self.kmeshgrid[i] / self.kabs


In [ ]:
t_grid = np.linspace(-25e-15, 25e-15, 20)
vacem.calculate_vacuum_current(t_grid)

In [5]:
Ntot = vacem.calculate_total_signal()

In [7]:
vacem.E_out

<generator object VacuumEmission.allocate_fields.<locals>.<genexpr> at 0x761d254d8820>

In [6]:
print(id(vacem.E_out[0]))
print(id(vacem.Ex))

TypeError: 'generator' object is not subscriptable

In [7]:
vacem.U1_acc_x

array([[[0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        ...,
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        ...,
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        ...,
        [0.+

In [6]:
Ntot

array(0.)

In [14]:
np.sum(np.isnan(vacem.U2_acc_x))

np.int64(0)

In [8]:
np.where(np.isnan(vacem.jx))

(array([0]), array([0]), array([0]))

In [5]:
t = 25e-15
Ex = field.calculate_field(t)

In [6]:
nx, ny, nz = x.size, y.size, z.size

plt.figure()
plt.pcolormesh(x.ravel(), y.ravel(), Ex[:,:,nz//2].T)
plt.colorbar()
plt.show()

TypeError: 'NoneType' object is not subscriptable

<Figure size 640x480 with 0 Axes>

In [19]:
members = dict(inspect.getmembers(field, lambda a:not(inspect.isroutine(a))))
for name,val in members.items():
    print(f"{name}: {sys.getsizeof(val)}")

# names = [name for name in dir(field)
#          if not name.startswith("__") and not inspect.isroutine(field.__dict__[name])]
# print(names)
# for name in names:
#     print(f"{name}: {sys.getsizeof(field.__dir__[name])}")

B0: 24
E: 29428312
E0: 24
R: 29428312
__class__: 1704
__dict__: 1584
__doc__: 722
__module__: 64
__weakref__: 16
beta: 24
focus_t: 24
focus_x: 64
grid: 64
grid_shape: 88
k: 24
lmbd: 24
omega: 24
phase0: 24
phase_no_t: 29428312
phi: 24
r2: 29428312
rotation: 232
rotation_bwd: 232
rotation_bwd_m: 128
rotation_m: 128
t0: 24
tau: 24
theta: 24
w: 29428312
w0: 24
x: 29428312
x0: 24
x_: 144
y: 29428312
y0: 24
y_: 144
z: 29428312
z0: 24
zR: 24
z_: 144


In [20]:
144**3

2985984

In [8]:
x = np.ones(10000)*2
y = np.ones(10000)*3

c = []
for i in range(2):
    val = ne.evaluate("i*x + y")
    c.append(val)

In [9]:
print(c)

[array([3., 3., 3., ..., 3., 3., 3.]), array([5., 5., 5., ..., 5., 5., 5.])]


In [10]:
for el in c:
    print(sys.getsizeof(el))

80112
80112


In [9]:
a = np.ones(100)*2
b = np.ones(100)*3

for i in range(2):
    d = ne.evaluate('a+b', local_dict={'a': np.zeros(100)})
    print(d)

[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3.]


In [6]:
np.savez(fn, b=b)

In [7]:
data = np.load(fn)
list(data.keys())

['b']

In [6]:
a = np.ones(100)*10
b = np.ones(100)
c = 'a + b'
ex = f'{c} + 1'
ne.evaluate(ex)

array([12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.,
       12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.,
       12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.,
       12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.,
       12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.,
       12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.,
       12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.,
       12., 12., 12., 12., 12., 12., 12., 12., 12.])